### ISSUE TITLE
extra ":status" header with https

### ISSUE THREAD

**Issue by nivekuil** [gnarroway/hato#44] opened 2022-07-16 06:49 UTC
`(:headers (hato.client/get "https://example.com"))`

```
{"x-cache" "HIT",
 "content-encoding" "gzip",
 "server" "ECS (sec/9795)",
 "age" "587885",
 "content-type" "text/html; charset=UTF-8",
 "content-length" "648",
 "accept-ranges" "bytes",
 "expires" "Sat, 23 Jul 2022 06:47:49 GMT",
 "etag" "\"3147526947\"",
 ":status" "200",
 "date" "Sat, 16 Jul 2022 06:47:49 GMT",
 "vary" "Accept-Encoding",
 "last-modified" "Thu, 17 Oct 2019 07:18:26 GMT",
 "cache-control" "max-age=604800"}
```
There's an extra `":status"` key in there, looks like it might be a bug? Odd thing is it doesn't exist without https, e.g. `(:headers (hato.client/get "http://example.com"))`

**Comment by gnarroway** [comment] 2022-08-08 02:20
Hi, thanks for raising this.

I dug into this and it is was a bit confusing as it "looks" like a Clojure keyword, but actually it was not.

To illustrate, the extra header shows up even if you use the Java library directly, with no Hato:

```clojure
(comment
  (def client (.build (HttpClient/newBuilder)))
  (def req (.build (HttpRequest/newBuilder (URI. "https://google.com"))))
  (def res (.send client req (HttpResponse$BodyHandlers/discarding)))
  (.map (.headers res))
  )
=>
...
{":status" ["301"],
...
```

After debugging, it appears it is used in [Steam.java](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.net.http/share/classes/jdk/internal/net/http/Stream.java#L432). 

The header is added directly from the response at [Stream.onDecoded](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.net.http/share/classes/jdk/internal/net/http/Stream.java#L1368)

Digging a bit further, it seems to be similar to "pseudo headers" as used in http2 ([tangential  stackoverflow discussion](https://stackoverflow.com/questions/70502726/what-is-the-purpose-of-http2-pseudo-headers-authority-method)), which is why you don't see it on plain http. Similarly you don't see it if you set `:version :http-1.1` 

Therefore, closing this issue as it seems to be working as intended.

**Closed by gnarroway** 2022-08-08 02:20 UTC

**Comment by nivekuil** [comment] 2022-08-08 03:27
Got it, thanks for info about pseudo headers, I really thought it was a keyword sneaking in there. For reference these need to be stripped when proxying the request to a HTTP1 client because colon isn't a valid character in a header.
